// Fails when a shipped surface still names the upstream product, or when a
// brand-pack slot is empty on a customer artifact.
//
// Two modes, same shape as check-distribution:
//
//   pnpm check:brand            every leak or empty slot is named in INCOMPLETE
//   pnpm check:brand --release  INCOMPLETE must be empty
//
// Authority: docs/plans/2026-08-25-002-brand-pack-plan.md
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { extname, join, relative, sep } from "node:path";
import { pathToFileURL } from "node:url";
import { parse as parseYaml } from "yaml";

const UNSET = "unset";

/** Directories skipped at every depth (build output, deps). */
export const ALWAYS_SKIP_DIR = new Set([
  "node_modules",
  "vendor",
  "testing",
  "dist",
  "dist-server",
  "dist-companion",
  "release",
  "coverage",
  ".next",
  "android",
]);

/** Top-level only — `apps/docs` is a shipped docs site, root `docs/` is not. */
export const TOP_SKIP_DIR = new Set(["docs", "tools", "third_party", "build"]);

const ALLOW_HIDDEN_DIRS = new Set([".github"]);

const SKIP_ROOT_FILES = new Set(["NOTICE", "LICENSE", "CONTRIBUTING.md", "README.md", "AGENTS.md"]);

/** Generated by `wrangler types`; gitignored. Scanning it would fail CI on a dirty Worker checkout. */
const SKIP_FILES = new Set(["worker-configuration.d.ts"]);

const READABLE = new Set([
  ".ts",
  ".tsx",
  ".mjs",
  ".cjs",
  ".js",
  ".jsx",
  ".yml",
  ".yaml",
  ".json",
  ".jsonc",
  ".html",
  ".swift",
  ".plist",
  ".md",
  ".mdx",
  ".txt",
  ".example",
]);

const HASH_COMMENT_EXT = new Set([".yml", ".yaml", ".jsonc"]);

function isTestPath(rel) {
  return (
    /\.test\.(ts|tsx|mjs|cjs|js)$/.test(rel) ||
    /\.node-test\.(mjs|cjs|js)$/.test(rel) ||
    /(?:^|\/)(?:test|Tests|__tests__)(?:\/|$)/.test(rel) ||
    rel.startsWith("scripts/check-brand") ||
    rel.startsWith("scripts/check-distribution")
  );
}

function isCommentLine(line, ext = "") {
  const t = line.trim();
  if (t.startsWith("#!")) return true;
  if (t.startsWith("//") || t.startsWith("*") || t.startsWith("/*") || t.startsWith("<!--")) return true;
  if (t.startsWith("#") && HASH_COMMENT_EXT.has(ext)) return true;
  return false;
}

function isHealthProbeWire(line) {
  return /openmausbot-control-plane/.test(line) && !/OpenMausBot|OpenMausMobile|OpenMaus |openmausbot\.com\b/.test(line);
}

/** Markers that identify the upstream product or their infrastructure. */
export function brandLeaks(
  text,
  { dataDirectorySet = false, executableNameSet = false, inheritedProtocol = false, ext = "" } = {},
) {
  const markers = [
    { pattern: /OpenMausBot/, what: "upstream product name" },
    { pattern: /OpenMausMobile/, what: "upstream companion name" },
    { pattern: /OpenMaus /, what: "upstream short name" },
    { pattern: /milind-soni/i, what: "upstream's GitHub account" },
    { pattern: /milindsoni201/i, what: "upstream's workers.dev subdomain" },
    { pattern: /openmausbot-releases/, what: "upstream's release feed" },
    { pattern: /openmausbot-teams/, what: "upstream's team library" },
    { pattern: /openmausbot\.com\b/, what: "upstream hosted domain" },
    { pattern: /🐭/, what: "crash-page mouse" },
  ];
  if (dataDirectorySet) {
    markers.push({ pattern: /["']\.openmausbot["']/, what: "historical data-dir default" });
  }
  if (executableNameSet) {
    markers.push({ pattern: /executableName:\s*openmausbot/, what: "upstream Linux executable name" });
  }
  if (inheritedProtocol) {
    markers.push({ pattern: /openmausbot:\/\//, what: "inherited protocol scheme" });
  }
  const hits = [];
  text.split(/\r?\n/).forEach((line, index) => {
    if (isCommentLine(line, ext)) return;
    if (isHealthProbeWire(line)) return;
    if (/openmaus\.team/.test(line) && !/OpenMausBot|OpenMausMobile|OpenMaus |openmausbot\.com\b/.test(line)) return;
    const marker = markers.find(({ pattern }) => pattern.test(line));
    if (marker) hits.push({ line: index + 1, what: marker.what, text: line.trim() });
  });
  return hits;
}

export function parseBrandProfile(source) {
  const field = (name) => {
    const match = source.match(new RegExp(`${name}:\\s*(UNSET|null|true|false|"([^"]*)")`));
    if (!match) return undefined;
    if (match[1] === "UNSET") return UNSET;
    if (match[1] === "null") return null;
    if (match[1] === "true") return true;
    if (match[1] === "false") return false;
    return match[2];
  };
  return {
    productName: field("productName"),
    companyName: field("companyName"),
    companionName: field("companionName"),
    defaultSkin: field("defaultSkin"),
    appId: field("appId"),
    dataDirectoryName: field("dataDirectoryName"),
    protocolDisplayName: field("protocolDisplayName"),
    protocolScheme: field("protocolScheme"),
    executableName: field("executableName"),
    speechHelperName: field("speechHelperName"),
    recorderHelperName: field("recorderHelperName"),
    httpUserAgent: field("httpUserAgent"),
    homepage: field("homepage"),
    authorName: field("authorName"),
    authorEmail: field("authorEmail"),
    docsBaseUrl: field("docsBaseUrl"),
    emailFromAddress: field("emailFromAddress"),
    controlPlaneUrl: field("controlPlaneUrl"),
    companionHostSuffix: field("companionHostSuffix"),
    publish: field("publish"),
    composioBrokerUrl: field("composioBrokerUrl"),
    teamLibrary: field("teamLibrary"),
    showUpdateDownload: field("showUpdateDownload"),
    iconsDir: field("iconsDir"),
    mascotDir: field("mascotDir"),
  };
}

function skipDirectory(name, parentRel) {
  if (ALWAYS_SKIP_DIR.has(name)) return true;
  if (name.startsWith(".") && !ALLOW_HIDDEN_DIRS.has(name)) return true;
  if (!parentRel && TOP_SKIP_DIR.has(name)) return true;
  return false;
}

function* walk(cwd) {
  const stack = [{ dir: cwd, rel: "" }];
  while (stack.length > 0) {
    const { dir: current, rel: parentRel } = stack.pop();
    if (!existsSync(current)) continue;
    for (const entry of readdirSync(current)) {
      const full = join(current, entry);
      let dir = false;
      try {
        dir = statSync(full).isDirectory();
      } catch {
        continue;
      }
      const rel = parentRel ? `${parentRel}/${entry}` : entry;
      if (dir) {
        if (skipDirectory(entry, parentRel)) continue;
        stack.push({ dir: full, rel });
        continue;
      }
      if (!parentRel && SKIP_ROOT_FILES.has(entry)) continue;
      if (SKIP_FILES.has(entry)) continue;
      yield full;
    }
  }
}

function assetCount(dir) {
  if (!existsSync(dir)) return 0;
  return readdirSync(dir).filter((name) => name !== ".gitkeep" && name !== "index.ts").length;
}

function scan(cwd, profile) {
  const found = new Map();
  const opts = {
    dataDirectorySet: profile.dataDirectoryName !== UNSET,
    executableNameSet: profile.executableName !== UNSET,
    inheritedProtocol: profile.protocolScheme !== UNSET && profile.protocolScheme !== "openmausbot",
  };
  for (const path of walk(cwd)) {
    const rel = relative(cwd, path).split(sep).join("/");
    const ext = extname(path);
    if (isTestPath(rel) || !READABLE.has(ext)) continue;
    const hits = brandLeaks(readFileSync(path, "utf8"), { ...opts, ext });
    if (hits.length > 0) found.set(rel, hits);
  }
  return found;
}

// Remaining leaks and empty slots. `count` is what keeps this from becoming a
// blanket exemption: a new OpenMausBot / milind hit in an already-listed file
// still fails. Slot-only rows use count 0.
export const INCOMPLETE = [
  { slot: "appId", file: "brand/profile.ts", count: 0, reason: "lock-once identity still unset" },
  { slot: "dataDirectoryName", file: "brand/profile.ts", count: 0, reason: "default is still ~/.openmausbot" },
  { slot: "protocolDisplayName", file: "brand/profile.ts", count: 0, reason: "protocol display name still unset" },
  { slot: "protocolScheme", file: "brand/profile.ts", count: 0, reason: "scheme keep-or-replace still unset" },
  { slot: "executableName", file: "brand/profile.ts", count: 0, reason: "Linux binary still inherited" },
  { slot: "speechHelperName", file: "brand/profile.ts", count: 0, reason: "macOS speech helper still OpenMausBot Speech.app" },
  { slot: "recorderHelperName", file: "brand/profile.ts", count: 0, reason: "macOS recorder helper still OpenMausBot Recorder.app" },
  { slot: "httpUserAgent", file: "brand/profile.ts", count: 0, reason: "outbound UA still OpenMausBot-skills" },
  { slot: "homepage", file: "brand/profile.ts", count: 0, reason: "installer homepage still upstream's" },
  { slot: "authorName", file: "brand/profile.ts", count: 0, reason: "installer author still upstream's" },
  { slot: "authorEmail", file: "brand/profile.ts", count: 0, reason: "installer email still upstream's" },
  { slot: "docsBaseUrl", file: "brand/profile.ts", count: 0, reason: "in-app docs links stay hidden until we have a URL" },
  { slot: "emailFromAddress", file: "brand/profile.ts", count: 0, reason: "OTP mailbox still wrangler noreply@openmausbot.com" },
  { slot: "controlPlaneUrl", file: "brand/profile.ts", count: 0, reason: "auth origin still accounts.openmausbot.com" },
  { slot: "companionHostSuffix", file: "brand/profile.ts", count: 0, reason: "managed companion hosts still openmausbot.com" },
  { slot: "publish", file: "brand/profile.ts", count: 0, reason: "no update feed until 004 plugs our repo" },
  { slot: "composioBrokerUrl", file: "brand/profile.ts", count: 0, reason: "packaged Composio fallback is still milind" },
  { slot: "companionName", file: "brand/profile.ts", count: 0, reason: "phone name falls back to productName; iOS strings remain" },
  { slot: "icons", file: "brand/icons", count: 0, reason: "brand/icons/ has no artwork" },
  { slot: "mascot", file: "brand/mascot", count: 0, reason: "brand/mascot/ has no drawing" },
  { slot: "productName", file: ".github/workflows/package-linux.yml", count: 11, reason: "Linux package artifacts still named OpenMausBot" },
  { slot: "publish", file: ".github/workflows/package-win.yml", count: 2, reason: "workflow still mentions openmausbot-releases (fail-if-present gate)" },
  { slot: "productName", file: ".github/workflows/check-upstream-license.yml", count: 1, reason: "fetch URL still names milind-soni/OpenMausBot" },
  { slot: "publish", file: ".github/workflows/release.yml", count: 58, reason: "upstream release workflow still names their feed and product" },
  { slot: "productName", file: "apps/docs/README.md", count: 6, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/app/layout.tsx", count: 4, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/components/brand-title.tsx", count: 1, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/changelog/index.mdx", count: 2, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/computers/cloud-and-vps.mdx", count: 3, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/computers/index.mdx", count: 3, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/computers/local-computer.mdx", count: 2, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/computers/local-vm.mdx", count: 6, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/connected-apps/index.mdx", count: 4, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/connected-apps/multiple-accounts.mdx", count: 2, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/connected-apps/self-hosted-composio.mdx", count: 2, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/contributing/index.mdx", count: 1, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/features/approvals-and-inspector.mdx", count: 4, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/features/automation.mdx", count: 4, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/features/chat-and-teams.mdx", count: 1, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/features/index.mdx", count: 2, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/features/voice-and-memory.mdx", count: 1, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/getting-started/configuration.mdx", count: 4, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/getting-started/first-bot.mdx", count: 3, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/getting-started/installation.mdx", count: 11, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/getting-started/quick-tour.mdx", count: 2, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/index.mdx", count: 5, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/meta.json", count: 1, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/mobile/android-control.mdx", count: 1, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/mobile/ios-companion.mdx", count: 3, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/providers/index.mdx", count: 5, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/providers/troubleshooting.mdx", count: 4, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/security/index.mdx", count: 2, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/security/permissions-and-secrets.mdx", count: 3, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/self-hosting/data-and-backups.mdx", count: 3, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/self-hosting/index.mdx", count: 4, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/self-hosting/networking.mdx", count: 1, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/troubleshooting/connected-apps.mdx", count: 1, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/troubleshooting/index.mdx", count: 2, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/troubleshooting/startup-and-ports.mdx", count: 4, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/content/docs/troubleshooting/updates.mdx", count: 8, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/lib/layout.shared.tsx", count: 2, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "apps/docs/lib/shared.ts", count: 3, reason: "docs site still names the upstream product" },
  { slot: "productName", file: "cloudflare/composio-broker/README.md", count: 1, reason: "Worker readme still names the upstream product" },
  { slot: "productName", file: "cloudflare/control-plane/README.md", count: 1, reason: "Worker readme still names the upstream product" },
  { slot: "controlPlaneUrl", file: "cloudflare/control-plane/wrangler.jsonc", count: 5, reason: "Worker host / mailbox still openmausbot.com" },
  { slot: "productName", file: "cloudflare/inference-broker/README.md", count: 1, reason: "Worker readme still names the upstream product" },
  { slot: "productName", file: "electron-builder.yml", count: 23, reason: "parent packager YAML still names OpenMausBot (overlay does not rewrite it)" },
  { slot: "recorderHelperName", file: "electron/build-recorder-helper.mjs", count: 1, reason: "bundle name still OpenMausBot Recorder.app" },
  { slot: "speechHelperName", file: "electron/build-speech-helper.mjs", count: 1, reason: "bundle name still OpenMausBot Speech.app" },
  { slot: "composioBrokerUrl", file: "electron/main.mjs", count: 2, reason: "packaged Composio fallback is still milind" },
  { slot: "recorderHelperName", file: "electron/resources/recorder-helper-Info.plist", count: 4, reason: "helper identity still names OpenMausBot" },
  { slot: "recorderHelperName", file: "electron/resources/recorder-helper.swift", count: 1, reason: "Accessibility prompt still names OpenMausBot Recorder" },
  { slot: "speechHelperName", file: "electron/resources/speech-helper-Info.plist", count: 4, reason: "helper identity still names OpenMausBot" },
  { slot: "recorderHelperName", file: "electron/skill-recorder.mjs", count: 1, reason: "packaged bundle name still OpenMausBot Recorder.app" },
  { slot: "speechHelperName", file: "electron/speech.mjs", count: 1, reason: "packaged bundle name still OpenMausBot Speech.app" },
  { slot: "companionName", file: "ios/App/AgentProfileView.swift", count: 1, reason: "iOS copy still names the upstream product" },
  { slot: "companionName", file: "ios/App/ConnectedAppsView.swift", count: 2, reason: "iOS connected-apps copy still names the upstream product" },
  { slot: "companionName", file: "ios/App/OnboardingViews.swift", count: 4, reason: "iOS onboarding copy still names the upstream product" },
  { slot: "companionName", file: "ios/App/PairingScanner.swift", count: 1, reason: "iOS pairing scanner still names the upstream product" },
  { slot: "companionName", file: "ios/App/PairingView.swift", count: 3, reason: "iOS pairing copy still names the upstream product" },
  { slot: "companionName", file: "ios/App/SettingsView.swift", count: 4, reason: "iOS settings copy still names OpenMausMobile / OpenMausBot" },
  { slot: "companionName", file: "ios/App/SpeechDictation.swift", count: 2, reason: "iOS dictation copy still names OpenMausMobile" },
  { slot: "companionName", file: "ios/App/TasksRoutinesView.swift", count: 2, reason: "iOS tasks copy still names the upstream product" },
  { slot: "companionName", file: "ios/AppStore/RELEASE.md", count: 3, reason: "App Store release notes still name the upstream product" },
  { slot: "companionName", file: "ios/AppStore/en-US/description.txt", count: 5, reason: "App Store description still names the upstream product" },
  { slot: "companionName", file: "ios/AppStore/en-US/promotional_text.txt", count: 1, reason: "App Store promo still names the upstream product" },
  { slot: "companionName", file: "ios/AppStore/en-US/release_notes.txt", count: 2, reason: "App Store release notes still name OpenMausMobile" },
  { slot: "companionName", file: "ios/AppStore/privacy-answers.md", count: 2, reason: "privacy answers still name the upstream product" },
  { slot: "companionName", file: "ios/AppStore/review-notes.md", count: 5, reason: "review notes still name the upstream product" },
  { slot: "companionName", file: "ios/README.md", count: 3, reason: "iOS readme still names the upstream product" },
  { slot: "companionName", file: "ios/Sources/CompanionCore/Client.swift", count: 1, reason: "client error copy still names the upstream product" },
  { slot: "companionName", file: "ios/Sources/CompanionCore/Failover.swift", count: 1, reason: "failover copy still names the upstream product" },
  { slot: "companionName", file: "ios/TESTING.md", count: 7, reason: "iOS testing notes still name the upstream product" },
  { slot: "companionName", file: "ios/Widgets/Info.plist", count: 1, reason: "widget display name still OpenMausMobile" },
  { slot: "companionName", file: "ios/project.yml", count: 7, reason: "XcodeGen display names still OpenMausMobile / OpenMausBot" },
  { slot: "homepage", file: "package.json", count: 3, reason: "homepage, repository and author still point at milind-soni" },
  { slot: "httpUserAgent", file: "server/distribution.ts", count: 1, reason: "outbound UA still OpenMausBot-skills" },
  { slot: "appId", file: "server/local-computer.ts", count: 1, reason: "macOS Application Support fallback still lists OpenMausBot" },
  { slot: "productName", file: "server/checkpoints.ts", count: 3, reason: "shadow-git identity still names OpenMausBot" },
  { slot: "productName", file: "scripts/clean.mjs", count: 1, reason: "packager still names OpenMausBot helper bundles" },
  { slot: "productName", file: "scripts/check-upstream-license.mjs", count: 1, reason: "clone URL still names milind-soni/OpenMausBot" },
  { slot: "productName", file: "scripts/cua-linux-release.mjs", count: 1, reason: "Cua packager still names the upstream product" },
  { slot: "productName", file: "scripts/generate-cua-sbom.mjs", count: 3, reason: "SBOM still names the upstream product" },
  { slot: "productName", file: "scripts/prepare-cua.mjs", count: 1, reason: "packager user-agent still OpenMausBot-packager" },
  { slot: "productName", file: "scripts/smoke-cua-x11-input.mjs", count: 1, reason: "smoke script still names the upstream product" },
  { slot: "productName", file: "scripts/smoke-deb-upgrade.mjs", count: 5, reason: "deb smoke still names OpenMausBot artifacts" },
  { slot: "productName", file: "scripts/smoke-linux-package.mjs", count: 4, reason: "Linux smoke still names OpenMausBot artifacts" },
  { slot: "productName", file: "skills/phone-harness/SKILL.md", count: 1, reason: "shipped skill still names the upstream product" },
  { slot: "productName", file: "skills/phone-harness/agents/openai.yaml", count: 1, reason: "shipped skill still names the upstream product" },
  { slot: "productName", file: ".github/workflows/docker.yml", count: 1, reason: "Docker workflow still names milind-soni" },
  { slot: "publish", file: ".github/workflows/sync-published-release.yml", count: 29, reason: "upstream sync-release workflow still names their product and GitHub account" },
  { slot: "productName", file: "apps/docs/components/release-changelog.tsx", count: 6, reason: "docs changelog still names the upstream product" },
  { slot: "productName", file: "deploy/docker-compose.yml", count: 1, reason: "compose image still names the upstream product" },
  { slot: "productName", file: "electron/browser-host.cjs", count: 1, reason: "browser host still names the upstream product" },
  { slot: "productName", file: "electron/browser-snapshot.cjs", count: 1, reason: "browser snapshot still names the upstream product" },
  { slot: "productName", file: "electron/browser-surface.cjs", count: 2, reason: "browser surface still names the upstream product" },
  { slot: "productName", file: "electron/desktop-workspace.cjs", count: 1, reason: "desktop workspace still names the upstream product" },
  { slot: "productName", file: "enterprise/README.md", count: 1, reason: "enterprise readme still names the upstream product" },
  { slot: "productName", file: "enterprise/server/license.ts", count: 2, reason: "enterprise license copy still names the upstream product" },
  { slot: "companionName", file: "ios/App/AttachmentViews.swift", count: 2, reason: "iOS attachments copy still names the upstream product" },
  { slot: "companionName", file: "ios/App/Session.swift", count: 3, reason: "iOS session copy still names the upstream product" },
  { slot: "companionName", file: "ios/ShareExtension/ShareItemLoader.swift", count: 2, reason: "share extension still names the upstream product" },
  { slot: "companionName", file: "ios/ShareExtension/ShareRootView.swift", count: 1, reason: "share extension still names the upstream product" },
  { slot: "companionName", file: "ios/ShareExtension/ShareViewModel.swift", count: 6, reason: "share extension still names the upstream product" },
  { slot: "productName", file: "scripts/build-browser-snapshot.mjs", count: 1, reason: "browser snapshot packager still names the upstream product" },
  { slot: "productName", file: "scripts/control-omb.ts", count: 2, reason: "control script still names the upstream product" },
  { slot: "productName", file: "scripts/generate-locale.mjs", count: 2, reason: "locale generator still names the upstream product" },
  { slot: "productName", file: "scripts/mcp-server.ts", count: 19, reason: "shipped MCP server still names the upstream product" },
  { slot: "productName", file: "scripts/smoke-deb-command.mjs", count: 2, reason: "deb smoke still names OpenMausBot artifacts" },
  { slot: "productName", file: "scripts/smoke-linux-update.mjs", count: 2, reason: "Linux update smoke still names OpenMausBot artifacts" },
  { slot: "productName", file: "scripts/verify-linux-package.mjs", count: 2, reason: "Linux package verify still names OpenMausBot artifacts" },
  { slot: "productName", file: "server/browser-connection.ts", count: 1, reason: "browser connection still names the upstream product" },
  { slot: "productName", file: "server/browser-lifecycle-cleanup.ts", count: 1, reason: "browser cleanup still names the upstream product" },
  { slot: "productName", file: "server/claude-update.ts", count: 1, reason: "Claude update copy still names the upstream product" },
  { slot: "productName", file: "server/harness/bus.ts", count: 1, reason: "event bus still names the upstream product" },
  { slot: "productName", file: "server/index.ts", count: 9, reason: "harness still names the upstream product in a few strings" },
  { slot: "productName", file: "server/mcp-probe.ts", count: 1, reason: "MCP probe still names the upstream product" },
  { slot: "productName", file: "server/mcp-registry.ts", count: 1, reason: "MCP registry still names the upstream product" },
  { slot: "productName", file: "server/pair-cli.ts", count: 1, reason: "pair CLI still names the upstream product" },
  { slot: "productName", file: "server/routine-requests.ts", count: 1, reason: "routine requests still name the upstream product" },
  { slot: "productName", file: "server/store.ts", count: 1, reason: "store comments still name the upstream product" },
  { slot: "productName", file: "skills/create-verification-skill/SKILL.md", count: 1, reason: "shipped skill still names the upstream product" },
  { slot: "productName", file: "src/components/BrowserPanel.tsx", count: 3, reason: "browser panel still names the upstream product" },
  { slot: "productName", file: "src/components/ComputerPanel.tsx", count: 6, reason: "computer panel still names the upstream product" },
  { slot: "productName", file: "src/components/LocalVmWorkspace.tsx", count: 4, reason: "Local VM workspace still names the upstream product" },
  { slot: "productName", file: "src/components/RoutineCalendarPage.tsx", count: 2, reason: "routine calendar still names the upstream product" },
  { slot: "productName", file: "src/components/SettingsModal.tsx", count: 2, reason: "settings modal still names the upstream product" },
  { slot: "productName", file: "src/components/SettingsPanel.tsx", count: 2, reason: "settings panel still names the upstream product" },
  { slot: "productName", file: "src/lib/computer-control.ts", count: 2, reason: "computer-control copy still names the upstream product" },
  { slot: "productName", file: "src/pair/PairPage.tsx", count: 1, reason: "pairing page still names the upstream product" },
];

const UNSET_SLOTS = [
  "companionName",
  "appId",
  "dataDirectoryName",
  "protocolDisplayName",
  "protocolScheme",
  "executableName",
  "speechHelperName",
  "recorderHelperName",
  "httpUserAgent",
  "homepage",
  "authorName",
  "authorEmail",
  "docsBaseUrl",
  "emailFromAddress",
  "controlPlaneUrl",
  "companionHostSuffix",
  "composioBrokerUrl",
];

export function evaluateBrand(cwd, { release = false } = {}) {
  const profileSource = readFileSync(join(cwd, "brand/profile.ts"), "utf8");
  const profile = parseBrandProfile(profileSource);
  const overlaySource = readFileSync(join(cwd, "brand/electron-builder.yml"), "utf8");
  const overlay = parseYaml(overlaySource);
  const failures = [];

  if (overlay.extends !== "../electron-builder.yml") {
    failures.push("brand/electron-builder.yml must extend ../electron-builder.yml");
  }
  if (overlay.productName !== profile.productName) {
    failures.push(
      `overlay productName ${JSON.stringify(overlay.productName)} !== profile ${JSON.stringify(profile.productName)}`,
    );
  }
  const baked = overlay.extraMetadata?.distribution?.productName;
  if (baked !== profile.productName) {
    failures.push(
      `overlay extraMetadata.distribution.productName ${JSON.stringify(baked)} !== profile ${JSON.stringify(profile.productName)}`,
    );
  }
  if (overlay.extraMetadata?.distribution?.teamLibrary !== profile.teamLibrary) {
    failures.push(
      `overlay extraMetadata.distribution.teamLibrary ${JSON.stringify(overlay.extraMetadata?.distribution?.teamLibrary)} !== profile ${JSON.stringify(profile.teamLibrary)}`,
    );
  }
  if (overlay.publish != null && !(Array.isArray(overlay.publish) && overlay.publish.length === 0)) {
    failures.push("overlay publish must be null (or []) until 004 plugs our repo");
  }
  if (overlaySource.includes("openmausbot-releases") || overlaySource.includes("milind-soni")) {
    failures.push("overlay still names upstream's publish feed");
  }
  if (overlay.appId && profile.appId === UNSET) {
    failures.push("overlay must not set appId while the slot is unset");
  }
  const bakedDistribution = overlay.extraMetadata?.distribution ?? {};
  for (const [key, value] of Object.entries(bakedDistribution)) {
    if (value === UNSET || value === "unset") {
      failures.push(`overlay extraMetadata.distribution.${key} must not bake the unset sentinel`);
    }
  }
  if (overlay.afterPack) {
    failures.push("overlay must not override afterPack — it must resolve from the project directory");
  }
  if (overlay.directories?.buildResources) {
    failures.push("overlay must not override directories.buildResources while icons are empty");
  }
  if (!existsSync(join(cwd, "scripts/after-pack.mjs"))) {
    failures.push("scripts/after-pack.mjs missing from the project directory");
  }
  if (!existsSync(join(cwd, "build"))) {
    failures.push("build/ missing from the project directory (parent directories.buildResources)");
  }

  const wranglerPath = join(cwd, "cloudflare/control-plane/wrangler.jsonc");
  if (existsSync(wranglerPath)) {
    const wranglerSource = readFileSync(wranglerPath, "utf8");
    if (profile.emailFromAddress !== UNSET && !wranglerSource.includes(profile.emailFromAddress)) {
      failures.push("wrangler.jsonc EMAIL_FROM must match brand/profile.ts emailFromAddress");
    }
    if (profile.controlPlaneUrl !== UNSET && !wranglerSource.includes(profile.controlPlaneUrl.replace(/^https:\/\//, ""))) {
      failures.push("wrangler.jsonc BETTER_AUTH_URL must match brand/profile.ts controlPlaneUrl");
    }
    if (profile.companionHostSuffix !== UNSET && !wranglerSource.includes(profile.companionHostSuffix)) {
      failures.push("wrangler.jsonc COMPANION_HOST_SUFFIX must match brand/profile.ts companionHostSuffix");
    }
    if (
      (profile.emailFromAddress !== UNSET || profile.controlPlaneUrl !== UNSET || profile.companionHostSuffix !== UNSET)
      && wranglerSource.includes("openmausbot.com")
    ) {
      failures.push("wrangler.jsonc still names openmausbot.com after control-plane slots were plugged");
    }
  }
  const bakedControlPlane = overlay.extraMetadata?.distribution?.controlPlaneUrl;
  if (profile.controlPlaneUrl === UNSET && bakedControlPlane) {
    failures.push("overlay must not bake controlPlaneUrl while the slot is unset");
  }
  if (profile.controlPlaneUrl !== UNSET && bakedControlPlane !== profile.controlPlaneUrl) {
    failures.push("overlay extraMetadata.distribution.controlPlaneUrl must match the profile");
  }

  const found = scan(cwd, profile);
  const unlisted = [];
  const drifted = [];
  for (const [file, hits] of [...found].sort()) {
    const entry = INCOMPLETE.find((candidate) => candidate.file === file && candidate.count > 0);
    if (!entry) {
      unlisted.push(`  ${file}\n${hits.map((h) => `      ${file}:${h.line} — ${h.what}`).join("\n")}`);
    } else if (entry.count !== hits.length) {
      drifted.push(`  ${file} — accepted ${entry.count}, found ${hits.length}`);
    }
  }
  const resolved = INCOMPLETE.filter((entry) => entry.count > 0 && !found.has(entry.file));

  const emptyIcons = assetCount(join(cwd, profile.iconsDir || "brand/icons")) === 0;
  const emptyMascot = assetCount(join(cwd, profile.mascotDir || "brand/mascot")) === 0;
  const missingSlots = [];
  for (const slot of UNSET_SLOTS) {
    if (profile[slot] === UNSET && !INCOMPLETE.some((entry) => entry.slot === slot)) {
      missingSlots.push(slot);
    }
  }
  if (profile.publish === null && !INCOMPLETE.some((entry) => entry.slot === "publish")) {
    missingSlots.push("publish");
  }
  if (emptyIcons && !INCOMPLETE.some((entry) => entry.slot === "icons")) missingSlots.push("icons");
  if (emptyMascot && !INCOMPLETE.some((entry) => entry.slot === "mascot")) missingSlots.push("mascot");

  if (unlisted.length > 0) {
    failures.push(
      `${unlisted.length} file(s) still name the upstream product and are not in INCOMPLETE:\n${unlisted.join("\n")}`,
    );
  }
  if (drifted.length > 0) {
    failures.push(`${drifted.length} INCOMPLETE file(s) gained or lost references:\n${drifted.join("\n")}`);
  }
  if (resolved.length > 0) {
    failures.push(
      `${resolved.length} INCOMPLETE file(s) no longer match anything:\n${resolved.map((e) => `  ${e.file}`).join("\n")}`,
    );
  }
  if (missingSlots.length > 0) {
    failures.push(`empty slots not listed in INCOMPLETE: ${missingSlots.join(", ")}`);
  }

  if (release && INCOMPLETE.length > 0) {
    failures.push(
      `${INCOMPLETE.length} brand slot(s) remain incomplete, and this is a release build:\n` +
        `${INCOMPLETE.map((entry) => `  ${entry.slot} — ${entry.reason}`).join("\n")}`,
    );
  }

  return { profile, found, failures, incomplete: INCOMPLETE };
}

function main() {
  const release = process.argv.includes("--release");
  const result = evaluateBrand(process.cwd(), { release });
  const total = [...result.found.values()].reduce((sum, hits) => sum + hits.length, 0);
  console.log(
    `Scanned the tree minus the denylist — ${total} remaining brand leak(s) in ${result.found.size} file(s); ${INCOMPLETE.length} INCOMPLETE slot(s).\n`,
  );
  for (const entry of INCOMPLETE) {
    console.log(`  ${entry.slot}${entry.file ? ` (${entry.file})` : ""}\n      ${entry.reason}`);
  }
  if (result.failures.length === 0) {
    console.log(release ? "\nBrand pack is complete. OK to ship." : "\nNo unlisted brand leaks. OK.");
    return;
  }
  console.error(`\n${result.failures.join("\n\n")}`);
  process.exit(1);
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  main();
}
